version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: samini
      MYSQL_PASSWORD: aaAA11!!
    ports:
      - "6604:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: room_backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:6604/test
      SPRING_DATASOURCE_USERNAME: samini
      SPRING_DATASOURCE_PASSWORD: aaAA11!!

  frontend:
    container_name: room_frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
