version: '3.8'

services:
  mysql-docker:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: aaAA11!!
      MYSQL_DATABASE: test
    ports:
      - "6604:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - react-spring
      - spring-mysql  # Ensure this network is defined
    depends_on:
      - mysql-docker
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://localhost:6604/test",
          "spring.datasource.username": "root",
          "spring.datasource.password": "aaAA11!!"
        }
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - react-spring
    depends_on:
      - backend
      
volumes:
  mysql-data: {}
  
networks:
  react-spring: {}
  spring-mysql: {}  # Define the network here
