version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - spring-mysql  
    depends_on:
      - mysqldb
      

  mysqldb:
    image: mysql:8.4
    networks:
      - spring-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: aaAA11!!
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
volumes:
  mysql-data: {}
  
networks:
  spring-mysql: {}  # Define the network here
