version: '3.8'

services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysql-docker
    environment:
      MYSQL_HOST: localhost
      MYSQL_URL: jdbc:mysql://localhost:6604/test
      MYSQL_USER: root
      MYSQL_PASSWORD: aaAA11!!

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql-docker:
    image: mysql:8.4
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: aaAA11!!
      MYSQL_DATABASE: test
    ports:
      - "6604:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
volumes:
  mysql-data:
