apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: sarwaraminy/spring-react-docker-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_SERVER
              value: "http://127.0.0.1"
