apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: development
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 90
      targetPort: 3000
      nodePort: 30001
  type: LoadBalancer
