apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: development
spec:
  selector:
    matchLabels:
      app: mysqldb
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "aaAA11!!"
            - name: MYSQL_DATABASE
              value: "test"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      

---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: development
spec:
  ports:
    - port: 3306
  selector:
    app: mysqldb
  clusterIP: None
