apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80  # The port that will be exposed
      targetPort: 8080  # The port on the pod
      nodePort: 30080  # The port on the node (optional, will be assigned if not specified)
  type: NodePort
