apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
  namespace: development
spec:
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
